### ISSUE TITLE
Failing tests on win-64

### ISSUE THREAD

**Issue by boldorider4** [quatrope/scikit-criteria#46]
There are failing tests on windows:

>                    INFO   FAILED tests/agg/test_moora.py::test_ReferencePointMOORA_kracka2010ranking - ... 
>                    INFO   FAILED tests/agg/test_moora.py::test_FullMultiplicativeForm_kracka2010ranking
>                    INFO   FAILED tests/agg/test_moora.py::test_FullMultiplicativeForm_only_minimize - a... 
>                    INFO   FAILED tests/agg/test_moora.py::test_FullMultiplicativeForm_only_maximize - a...
>                    INFO   FAILED tests/agg/test_moora.py::test_MultiMOORA_kracka2010ranking - assert False
>                    INFO   FAILED tests/agg/test_similarity.py::test_TOPSIS - assert False
>                    INFO   FAILED tests/agg/test_similarity.py::test_TOPSIS_tzeng2011multiple - assert F...
>                    INFO   FAILED tests/agg/test_simple.py::test_WeightedSumModel - assert False
>                    INFO   FAILED tests/agg/test_simple.py::test_WeightedSumModel_kracka2010ranking - as...
>                    INFO   FAILED tests/agg/test_simple.py::test_WeightedProductModel - assert False
>                    INFO   FAILED tests/agg/test_simple.py::test_WeightedProductModel_enwiki_1015567716
>                    INFO   FAILED tests/agg/test_simus.py::test_SIMUS_munier24metodo - assert False
>                    INFO   FAILED tests/core/test_dominance.py::test_DecisionMatrixDominanceAccessor_compare

These are failing due to following line

`assert result.values_equals(expected)`

This is because `result` and `expected`, which are of type `DecisionMatrix` and `RankResult` respectively, rely on `pandas.DataFrame` which is known to default to `int32` values on windows as opposed to `int64` when dealing with integer values. This issue is also discussed [here](https://stackoverflow.com/questions/64901822/why-do-pandas-integer-dtypes-not-behave-the-same-on-unix-and-windows).

Can you please fix the tests so that the `dtype` is enforced on `DecisionMatrix`?

**Comment by leliel12** [comment]
Unfortunately the automatic detection of data types is part of the expected behaviior of the project.

There are some prototypes we are using internally that take advantage of the type information to perform more accurate calculations for example using Manhattan or euclidean distance depending on whether the types are integers or floats respectively. so simply leaving the data type fixed in the decision matrix is not a feasible solution.

 this issue of Windows representing integers differently will probably have to be solved at the testing level and take into account this change of behavior in the underlying library (pandas).

**Comment by leliel12** [comment]
Fixed on release 0.8.7
