### ISSUE TITLE
SIMUS 

### ISSUE THREAD

**Issue by SalvatoreRa** [quatrope/scikit-criteria#48]
Hello,

I am trying to use the SIMUS model, let'say I have a matrix dm

```
import skcriteria as skc

dm = skc.mkdm(
    matrix=[
        [7, 5, 35],
        [5, 4, 26],
        [5, 6, 28],
        [3, 4, 36],
        [1, 7, 30],
        [5, 8, 30],
    ],
    objectives=[max, max, min],
    alternatives=["PE", "JN", "AA", "FX", "MM", "FN"],
    criteria=["ROE", "CAP", "RI"],
)

dm
```

How I can use SIMUS?

I have tried:
```

from skcriteria.madm import simus
import numpy as np

#alt1
simus = simus.simus(np.array(dm), objectives=[max, max, min])
#alt2
simus = simus.simus(dm, objectives=[max, max, min])
#alt3
simus = simus.simus(dm)

```
They all providing an error.

thank you very much

**Comment by leliel12** [comment]
You can use simus using the object oriented interface

```python
from skcriteria.madm import simus

dec = simus.SIMUS()  # first you need to instantiate the model with your configuration

# now you can evaluate your decision matrix with
dec.evaluate(dm)
```

I recommend you to watch the [Quick-Start tutorial of skcriteria](https://scikit-criteria.quatrope.org/en/latest/tutorial/quickstart.html)
to understand the general logic of the package

On the other hand, simus lacks a little bit of love since skcriteria uses [PuLP](https://coin-or.github.io/pulp/)  to solve linear programming when there are better packages like google-or.
packages li [or-tool](https://developers.google.com/optimization).

Finally I invite you to join the [skcriteria mailing list](https://groups.google.com/forum/#!forum/scikit-criteria), because the issues are intended for bug reports and not Q&A.

please close this issue if the answer was satisfactory

**Comment by leliel12** [comment]
the lower case function `simus()` is a low level interface of the method and objectives (as [1, -1] array) and the matrix (dm.matrix.to_nump()), but the class is much much more simple. Maybe in future i gonna hide the function to avoid confussion

**Comment by leliel12** [comment]
close because inactivity
